# Generated by Django 4.1.1 on 2022-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oredered',
        ),
        migrations.AddField(
            model_name='order',
            name='oredred',
            field=models.BooleanField(default=False),
        ),
    ]
