# Generated by Django 4.1.1 on 2022-09-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_order_oredered_order_oredred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredred',
            new_name='ordered',
        ),
    ]
