# Generated by Django 4.1.1 on 2022-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_saga_biography_saga_chap_start_saga_chap_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Sayen', 'Sayen'), ('Namek', 'Namek'), ('Terrien', 'Terrien'), ('Autres', 'Autres')], max_length=10),
        ),
    ]
