# Generated by Django 4.1.1 on 2022-09-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_place_alter_saga_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.place'),
        ),
        migrations.AddField(
            model_name='saga',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sagas'),
        ),
    ]
