# Generated by Django 4.1.1 on 2022-09-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_character_place_saga_place_alter_place_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='place',
        ),
    ]
