# Generated by Django 4.1.1 on 2022-09-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_character_activity_character_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saga',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.character'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.place'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='resume',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
