# Generated by Django 4.1.1 on 2022-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_saga_character_alter_saga_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='origin',
        ),
    ]
