# Generated by Django 4.1.1 on 2022-09-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_character_slug_place_slug_saga_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='saga',
            name='slug',
        ),
    ]
